# Generated by Django 3.2.3 on 2021-06-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stocksIDName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocksID', models.CharField(max_length=10)),
                ('stocksName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stocksTypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocksType', models.CharField(max_length=20)),
                ('stocksLink1', models.TextField(max_length=100)),
                ('stocksLink2', models.TextField(max_length=100)),
            ],
        ),
    ]
