# Generated by Django 3.2.3 on 2021-06-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksidname',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stockstypelink',
            options={'managed': False},
        ),
    ]
